import Link from 'next/link'

export const metadata = { title: 'Legal Disclaimer — LexIQ', description: 'LexIQ legal disclaimer — not a substitute for professional legal advice.' }

export default function LegalDisclaimerPage() {
  return (
    <div style={{ background: 'var(--navy)', color: '#f5f0e8', fontFamily: 'Georgia, serif', minHeight: '100vh' }}>
      <nav style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '18px 48px', borderBottom: '0.5px solid var(--border-gold)', background: 'rgba(10,22,40,0.95)', backdropFilter: 'blur(12px)' }}>
        <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: 10, textDecoration: 'none' }}>
          <div style={{ width: 36, height: 36, borderRadius: 8, background: 'var(--gold)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 18, color: 'var(--navy)', fontWeight: 'bold' }}>⚖</div>
          <div style={{ fontSize: 20, fontWeight: 'bold', color: '#f5f0e8', letterSpacing: 1 }}>Lex<span style={{ color: 'var(--gold)' }}>IQ</span></div>
        </Link>
        <Link href="/" style={{ fontSize: 13, color: 'var(--gold)', fontFamily: 'Inter, sans-serif', textDecoration: 'none' }}>← Back to Home</Link>
      </nav>

      <main style={{ maxWidth: 800, margin: '0 auto', padding: '72px 48px' }}>
        <div style={{ fontSize: 11, color: 'var(--gold)', letterSpacing: 2, textTransform: 'uppercase', fontFamily: 'Inter, sans-serif', marginBottom: 12 }}>Legal</div>
        <h1 style={{ fontSize: 40, marginBottom: 8, lineHeight: 1.2 }}>Legal Disclaimer</h1>
        <p style={{ fontSize: 13, color: 'var(--text-muted)', fontFamily: 'Inter, sans-serif', marginBottom: 24 }}>Last updated: April 2026</p>
        <div style={{ width: 60, height: 2, background: 'var(--gold)', marginBottom: 40, borderRadius: 2 }} />

        {/* Important notice box */}
        <div style={{ background: 'rgba(201,168,76,0.08)', border: '0.5px solid var(--gold)', borderRadius: 12, padding: '24px 28px', marginBottom: 48 }}>
          <div style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
            <span style={{ fontSize: 22 }}>⚠️</span>
            <div style={{ fontFamily: 'Inter, sans-serif', fontSize: 15, color: '#f5f0e8', lineHeight: 1.7 }}>
              <strong>LexIQ is not a law firm and does not provide legal advice.</strong> The information provided through this platform is for general educational and informational purposes only and should not be treated as formal legal counsel or professional legal opinion.
            </div>
          </div>
        </div>

        <div style={{ fontFamily: 'Inter, sans-serif', fontSize: 15, color: 'var(--text-muted)', lineHeight: 1.9 }}>
          {[
            {
              title: 'No Attorney-Client Relationship',
              body: 'Use of LexIQ does not create an attorney-client relationship between you and LexIQ or any of its operators. Responses generated by the platform are not legal opinions and cannot be relied upon as such in any legal proceeding.'
            },
            {
              title: 'Accuracy of Information',
              body: 'While we strive to provide accurate and up-to-date information based on Indian law, laws change frequently and the platform may not always reflect the most recent amendments, judicial interpretations, or government notifications. Always verify critical legal information from official sources such as India Code (indiacode.nic.in) or a qualified legal professional.'
            },
            {
              title: 'Consult a Legal Professional',
              body: 'For any situation involving potential legal liability, criminal charges, property disputes, contractual obligations, or any matter where your rights may be at stake — you must consult a qualified advocate or legal professional licensed to practice in the relevant jurisdiction.'
            },
            {
              title: 'Jurisdiction Limitations',
              body: 'LexIQ is designed specifically around Indian law. Information provided may not be applicable in other legal systems or jurisdictions. Do not apply LexIQ\'s guidance to matters governed by foreign laws.'
            },
            {
              title: 'Limitation of Liability',
              body: 'LexIQ and its operators expressly disclaim all liability for any loss, damage, or adverse outcome — direct or indirect — resulting from reliance on information provided through the platform. The platform is provided on an "as is" basis without warranties of accuracy, completeness, or fitness for a particular purpose.'
            },
          ].map((section) => (
            <div key={section.title} style={{ marginBottom: 32 }}>
              <h2 style={{ color: '#f5f0e8', fontSize: 18, marginBottom: 12, fontFamily: 'Georgia, serif' }}>{section.title}</h2>
              <p style={{ margin: 0 }}>{section.body}</p>
            </div>
          ))}
        </div>
      </main>

      <Footer />
    </div>
  )
}

function Footer() {
  return (
    <footer style={{ padding: '24px 48px', borderTop: '0.5px solid var(--border-gold)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', fontSize: 12, color: 'var(--text-muted)', fontFamily: 'Inter, sans-serif' }}>
      <span>LexIQ — India&apos;s Legal Intelligence Platform</span>
      <div style={{ display: 'flex', gap: 20 }}>
        {[['About', '/about'], ['Privacy Policy', '/privacy'], ['Terms of Use', '/terms'], ['Legal Disclaimer', '/legal-disclaimer']].map(([l, h]) => (
          <Link key={l} href={h} style={{ color: 'var(--text-muted)', textDecoration: 'none' }}>{l}</Link>
        ))}
        <span style={{ color: 'var(--gold)' }}>© 2026 LexIQ</span>
      </div>
    </footer>
  )
}
